# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84fa09c2bbee24636759d3d4e647fd79bab196f4adbaaf9936745c1c169fa21765813a86b5c52c3efafeeae70c2d076a77a63edde0252123f628227247b6de57

test:
  secret_key_base: 5fdc73e0f00aad1ef05581a1dc1a62401101b3142d9bae52411e41f7e9a50c93b742a2eda3c9bf0c10cd07ff9c847c79db59e4af74277db0fb512f304eb579be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
